id: I4D975185
ocr_import_info:
  timestamp: '2023-09-23T04:09:38.415782+00:00'
  batch_id: batch-9e7a
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Tenzin Jordhen
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-23 04:20:08.333482+00:00
last_modified: 2023-09-23 04:20:08.333491+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1NLM1157
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1NLM1157
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སེམས་དང་སེམས་བྱུང་གི་རྣམ་བཞག་ཅུང་ཟད་བཤད་པ་རང་རྒྱུད་གསལ་བའི་མེ་ལོང་སོགས།
  languages:
  - bo
  author: དཀོན་མཆོག་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.957937465442864
  ocr_word_median_confidence_index: 0.99761313
bases:
  I1NLM1157_001:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1NLM1157_001
      total_pages: 557
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I1NLM1157_001.txt
    statistics:
      ocr_word_median_confidence_index: 0.99761313
      ocr_word_mean_confidence_index: 0.957937465442864
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
